apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: netpol-mongo
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: mongodb
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: nginx
    ports:
    - protocol: TCP
      port: 80
